### ISSUE TITLE
Forced loose

### ISSUE THREAD

**Issue by Andrii-Ishchenko** [CatalinFrancu/nilatac#1]
It will be very convenient if you can add a list of forced loose moves on your site(moves where score == lost) on your site.

**Comment by CatalinFrancu** [comment]
Are you referring to the [opening book browser](http://catalin.francu.com/nilatac/book.php?query=e3)? (Please note that there is [much better research](http://magma.maths.usyd.edu.au/~watkins/LOSING_CHESS/) out there. Everything except **1. e3 b6** is solved.

**Comment by Andrii-Ishchenko** [comment]
Yes, i refer that page.
thanks for link
