### ISSUE TITLE
Nilatac binaries for Windows systems (executables files)

### ISSUE THREAD

**Issue by yellow-panther** [CatalinFrancu/nilatac#2]
Hellom
can you build a stable **Windows version 32/64 bit of Nilatac´s source code** https://github.com/CatalinFrancu/nilatac  please and host it here, too?

**Comment by CatalinFrancu** [comment]
Hi,

Not really - I have been Windows-free for over 10 years. Please feel free to give it a try. Some patching will probably be required, but not much.
